branches:
  only:
    - master
    - development
language: python
cache: pip
notifications:
  email: false
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
os:
  - linux
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -r tests/notebook_tests/requirements.txt
  - pip install -U numpy # force update of numpy
  - pip list
# command to run tests
script:
  - python -m unittest discover tests/integration_tests 
  - coverage run --rcfile=.coveragerc -m unittest discover tests/unit_tests
  - pip install .
  - python -m unittest discover tests/notebook_tests 
after_success: 
  - codeclimate-test-reporter --debug --token $CODECLIMATE_REPO_TOKEN
