# -*- coding: utf-8 -*-

# import os
# import sys
# sys.path.insert(0, os.path.abspath('../../'))

import bsym 

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',
    'myst_parser',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'nbsphinx'
]

# nbsphinx settings
nbsphinx_execute = 'auto'
nbsphinx_allow_errors = False
nbsphinx_kernel_name = 'python3'

# Hide prompts
nbsphinx_prompt_width = "0"

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'bsym'
copyright = '2017, Benjamin J. Morgan'
author = 'Benjamin J. Morgan'

# The version info for the project you're documenting
version = '.'.join(bsym.__version__.split('.')[:2])
release = bsym.__version__

# The language for content autogenerated by Sphinx
language = 'en'  

# List of patterns to ignore when looking for source files
exclude_patterns = ['_build', '**.ipynb_checkpoints']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files
html_static_path = ['_static']

# Custom sidebar templates
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# -- Options for HTMLHelp output ------------------------------------------
htmlhelp_basename = 'bsymdoc'

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {}

latex_documents = [
    (master_doc, 'bsym.tex', 'bsym Documentation',
     'Benjamin J. Morgan', 'manual'),
]

# -- Options for manual page output ---------------------------------------
man_pages = [
    (master_doc, 'bsym', 'bsym Documentation',
     [author], 1)
]

# -- Options for Texinfo output -------------------------------------------
texinfo_documents = [
    (master_doc, 'bsym', 'bsym Documentation',
     author, 'bsym', 'One line description of project.',
     'Miscellaneous'),
]
