name: Build

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [3.7,3.8,3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/notebook_tests/requirements.txt
        pip install -U numpy
        pip install pytest
        pip install pytest-cov
        pip list
    - name: Run tests
      run: |
        pytest tests/integration_tests
        pytest tests/notebook_tests
        pytest --cov-report xml --cov=tests/unit_tests
    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPO_TOKEN }}
        
        coverage run --rcfile=.coveragerc -m unittest discover tests/unit_tests
        pip install .
        pytest 
        python -m unittest discover tests/notebook_tests
    - name: Publish code coverage
      run: |
        codeclimate-test-reporter --debug --token ${{ secrets.CODECLIMATE_REPO_TOKEN }}
    
